### ISSUE TITLE
Angel Chest causes a fault for World Guard 7.0.4 Beta 1

### ISSUE THREAD

**Issue by TheSilverdown** [JEFF-Media-GbR/Spigot-AngelChest#29] opened 2020-07-16 22:34 UTC
I get this output error only when I add in Angel Chest 2.8.1, If I remove Angel Chest all is fine.

```
16.07 22:30:37 [Server] Server thread/WARN [WorldGuard] Loaded class com.sk89q.worldguard.bukkit.WorldGuardPlugin from AngelChest v2.8.1 which is not a depend, softdepend or loadbefore of this plugin.
16.07 22:30:37 [Server] Server thread/ERROR Could not load 'plugins/worldguard-bukkit-7.0.4-SNAPSHOT-dist.jar' in folder 'plugins'
16.07 22:30:37 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/squirrelid/cache/ProfileCache
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:382) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
16.07 22:30:37 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/squirrelid/cache/ProfileCache
16.07 22:30:37 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO ... 7 more
16.07 22:30:37 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.sk89q.squirrelid.cache.ProfileCache
16.07 22:30:37 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot-1.16.1.jar:git-Spigot-05da6fa-b0c6dfe]
16.07 22:30:37 [Server] INFO ... 7 more
```

**Comment by mfnalex** [comment] 2020-07-16 22:37
oh I am sorry. I only used the latest stable worldguard ~~7.2~~ 7.0.3, why are you using the beta?

BTW do you need the worldguard integration? Or don't you use the "disabled-worldguard-regions" setting?

**Comment by mfnalex** [comment] 2020-07-16 23:00
Oh, I just saw that 7.0.4 is marked as latest version for 1.16.1. When I checked, there was still 7.0.3 marked as 1.16.1 release and it worked fine. I will try it again with that version and see what I can do

**Comment by mfnalex** [comment] 2020-07-16 23:09
Actually I cannot reproduce the problem:

```
$ grep 'AngelChest\|WorldGuard' latest.log
[01:06:42] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.4-beta1;bc551da
[01:06:42] [Server thread/INFO]: [AngelChest] Loading AngelChest v2.9.0-SNAPSHOT
[01:06:52] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.4-beta1;bc551da
[01:06:52] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[01:06:52] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[01:06:52] [Server thread/INFO]: [WorldGuard] Loading region data...
[01:06:52] [Server thread/INFO]: [AngelChest] Enabling AngelChest v2.9.0-SNAPSHOT
[01:06:52] [Server thread/INFO]: [AngelChest] groups.yml does not exist, skipping custom group settings.
[01:06:52] [Server thread/INFO]: [AngelChest] Successfully hooked into WorldGuard 7+
[01:06:52] [Server thread/INFO]: [AngelChest] Loading AngelChest 21783282.yml
[01:06:53] [Server thread/WARN]: [AngelChest] =================================================
[01:06:53] [Server thread/WARN]: [AngelChest] There is a new version of AngelChest available!
[01:06:53] [Server thread/WARN]: [AngelChest] Latest : 2.8.1
[01:06:53] [Server thread/WARN]: [AngelChest] Current: 2.9.0-SNAPSHOT
[01:06:53] [Server thread/WARN]: [AngelChest] Please update to the newest version. Download:
[01:06:53] [Server thread/WARN]: [AngelChest] https://www.spigotmc.org/resources/1-12-1-15-angelchest.60383/
[01:06:53] [Server thread/WARN]: [AngelChest] =================================================
[01:07:07] [Server thread/INFO]: [AngelChest] Disabling AngelChest v2.9.0-SNAPSHOT
[01:07:07] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.4-beta1;bc551da
[01:07:07] [Server thread/INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
```
Works fine with WorldGuard 7.0.4.

Please try this version of AngelChest: https://repo.jeff-media.de/maven2/de/jeff_media/AngelChest/2.9.0-SNAPSHOT/AngelChest-2.9.0-20200716.230903-8.jar

**Comment by mfnalex** [comment] 2020-07-16 23:11
What's your WorldEdit version?

**Comment by TheSilverdown** [comment] 2020-07-16 23:38
worldedit-bukkit-7.2.0-beta-02.jar and worldguard-bukkit-7.0.4-beta1.jar

worldguard-bukkit-7.0.4-beta1.jar says for 1.16.1 only

**Comment by mfnalex** [comment] 2020-07-17 00:47
Can you try again with the new version on SpigotMC?

**Comment by TheSilverdown** [comment] 2020-07-17 01:22
Angel Chest Version 2.8.2 fixes the problem I was having :D, thank you!

**Comment by mfnalex** [comment] 2020-07-17 02:37
Awesome, thanks for the reply :)

**Closed as completed by mfnalex** 2020-07-17 02:37 UTC
